[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false

[theme]
primaryColor = "#e74c3c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[browser]
gatherUsageStats = false
